### ISSUE TITLE
Difficulty Rework

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#149]
# Reworking the DDC Difficulty Preset

With reference to [this link here.](https://community.bistudio.com/wiki/Arma_3_Difficulty_Menu)
Anything with bolded text is fixed. Those cannot/will not be changed.
### Difficulty

**AI Level: High**
**Reduced Damage: off**
Map Content:
Auto Report:
### Icons

Group Indicators: 
Friendly Tags:
Enemy Tags:
**Detected Mines: DISABLED DUE TO ACE**
**Command Icons: off - We don't use commands.**
Waypoints Icons:
### User Interface

Weapon Info:
Stance Indicator:
Stamina Bar:
Weapon Crosshair:
**Vision Aid: off**
**Squad Radar (Coming Soon): off**
### Camera

Third Person:
**Camera Shake: on**
### Other

**Score Table: on**
**Death Messages: on**
**VonID: on**
**Multiple Saves: off**

**Comment by Eogos** [comment]
weapon info, stamina bar, weapon crosshair, third person, friendly tags, detected mines, command and waypoint icons, and group indicators should all be on. Stance indicator I don't really care about, do whatever with that. I don't know what map content and auto report are so...

**Comment by SpazzMods** [comment]
AI Level: High
Reduced Damage: off
Map Content: off
Auto Report: off

Icons

Group Indicators: on
Friendly Tags: on
Enemy Tags: off
Detected Mines: off (player map markers can be placed so maybe people will pay attention)
Command Icons:
Waypoints Icons:

User Interface

Weapon Info: MagCount/FireMode
Stance Indicator: on
Stamina Bar: on
Weapon Crosshair: on
Vision Aid: off
Squad Radar (Coming Soon): off

Camera

Third Person: on
Camera Shake: on

Other

Score Table: on
Death Messages: on
VonID: on
Multiple Saves: off


My contribution to the lot

**Comment by PallyWoods** [comment]
Difficulty

AI Level: High
Reduced Damage: off
Map Content: ??
Auto Report: Off if this is the voice spotting thing that characters and AI do

Icons

**Group Indicators: Off**
**Friendly Tags: Off**
**Enemy Tags: Off**
Detected Mines: DISABLED DUE TO ACE
Command Icons: off - We don't use commands.
Waypoints Icons: undecided, I abuse them, but they can be helpful for ground ops

User Interface

**Weapon Info: Yes**
**Stance Indicator: Yes**
**Stamina Bar: YES**
**Weapon Crosshair: Off**
Vision Aid: off
Squad Radar (Coming Soon): off

Camera

**Third Person: On for CoOps, Off for PvPs (which I am planning on making in the coming weeks btw)**
Camera Shake: on

Other

Score Table: on
**Death Messages: Off**
VonID: on
Multiple Saves: off
