### ISSUE TITLE
Add more custom areas & caches

### ISSUE THREAD

**Issue by SchwererKonigstiger** [DeathDeliveryCorps/Operations#318]
Need to add more custom camps and etc, as listed below.

- [x] New camps around map
  - [x]  Add both hostile & friendly camps
- [ ] Add loot boxes throughout the towns
- [ ] Hide custom caches around msp
- [ ] Add a "Safe-Zone Spawn" - to be discussed
- [x] Hand-place damaged but usable vehicles around map

**Comment by Eogos** [comment]
IMO there doesn't need to be a safe-zone spawn, now that everyone knows about the enhanced movement thing (because it's on all servers) they'll already know they can climb on top of stuff even if they haven't played yet and the rest of us have gotten good enough that even when RNG fucks us and spawns a horde we can most likely survive.

**Comment by SchwererKonigstiger** [comment]
Closed, this is a permanently ongoing task.
